### ISSUE TITLE
What is 'darwin_lib', please check the catkin's build_depend and run_depend setting.

### ISSUE THREAD

**Issue by robotpilot** [ROBOTIS-OP/robotis_op_camera#1]
I have one question. What is 'darwin_lib' ? Is it dependence library file?
Please check the catkin's build_depend and run_depend setting, I send my building result below.

CMake Error at robotis_op_camera/CMakeLists.txt:27 (find_package):
  By not providing "Finddarwin_lib.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "darwin_lib", but CMake did not find one.

  Could not find a package configuration file provided by "darwin_lib" with
  any of the following names:

```
darwin_libConfig.cmake
darwin_lib-config.cmake
```

  Add the installation prefix of "darwin_lib" to CMAKE_PREFIX_PATH or set
  "darwin_lib_DIR" to a directory containing one of the above files.  If
  "darwin_lib" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by kdaun** [comment]
darwin_lib is the ROBOTIS framework for accessing e.g. the actuators and the camera. It is contained in the package robotis_op_framework.
Check if you downloaded this package. In the package there is a Finddarwin_lib.cmake. Copy this file into your CMake Module path (/usr/share/cmake-2.8/Modules).
You can check the overall instructions guide in the wiki, see [Installation on ROBOTIS OP2](https://github.com/ROBOTIS-OP/robotis_op_framework/wiki/Installation-on-ROBOTIS-OP2).

**Comment by robotpilot** [comment]
Thanks for your comments. Your information are useful for me. :)
